### ISSUE TITLE
MTextBox and MPasswordTextBox do not implement HasText with GWT 2.7.0-rc1

### ISSUE THREAD

**Issue by johnthad** [mgwt/mgwt#217]
I'm attempting to build my most current project with GWT 2.7.0-rc1 and MGWT 2.0.1-SNAPSHOT. Whatever class or interface used to bring in com.google.gwt.user.client.ui.HasText, it does not any longer. I have a view with two methods that return HasText so the activity won't care if they are TextBox vs MTextBox or PasswordTextBox vs MPasswordTextBox. The mgwt implementation of this view will not work with GWT 2.7.0-rc1 and MGWT 2.0.1-SNAPSHOT since HasText no longer implements HasText:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/thad/gwt-devel/gwt270rc1/mini/src/main/java/com/optix/mobile/client/activities/login/LoginViewGwtImpl.java:[76,12] incompatible types
  required: com.google.gwt.user.client.ui.HasText
  found:    com.googlecode.mgwt.ui.client.widget.input.MTextBox
[ERROR] /Users/thad/gwt-devel/gwt270rc1/mini/src/main/java/com/optix/mobile/client/activities/login/LoginViewGwtImpl.java:[81,12] incompatible types
  required: com.google.gwt.user.client.ui.HasText
  found:    com.googlecode.mgwt.ui.client.widget.input.MPasswordTextBox
[ERROR] /Users/thad/gwt-devel/gwt270rc1/mini/src/main/java/com/optix/mobile/client/activities/login/LoginViewGwtImpl.java:[86,12] incompatible types
  required: com.google.gwt.user.client.ui.HasText
  found:    com.googlecode.mgwt.ui.client.widget.input.MTextBox
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

My workaround is to substitute HasValue<String> for HasText, but I think MTextBox and MPasswordTextBoxs should implement HasText.

If you clone MGWT from GitHub, modify the pom.xml (line #19) to &lt;gwtversion&gt;2.7.0-rc1&lt;/gwtversion&gt;, and run `mvn javadoc:javadoc`, you'll see that the JavaDocs no longer show that HasText is implemented.
